language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test:coverage
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
    
after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls